#![allow(async_fn_in_trait)]

use http_body_util::Full;
use hyper::body::Bytes;
use hyper_util::client::legacy::Client;
use hyper_util::rt::TokioExecutor;
use tower_json_rpc::error::JsonRpcError;
use tower_json_rpc_derive::rpc;

#[rpc(client, namespace = "say")]
pub trait Say {
    #[method(name = "hello")]
    async fn say_hello(&self, name: String) -> Result<String, JsonRpcError>;
}

#[tokio::main]
async fn main() -> Result<(), JsonRpcError> {
    let client: Client<_, Full<Bytes>> = Client::builder(TokioExecutor::new()).build_http();

    // The SayClient trait is automatically generated by the #[rpc(client)] macro.
    // It extends any Service<Request<Full<Bytes>>> with RPC methods.
    let result = client.say_hello("test".into()).await?;

    // let result = client.rpc_call(SayRequest::SayHello {
    //     name: "test".into(),
    // });
    println!("Result: {}", result);

    Ok(())
}
